### ISSUE TITLE
Hey op, did you forget about this??

### ISSUE THREAD

**Issue by ArisuSanchez** [Doomsdayrs/wugin-de#1]
seems like theres no code, are you working on this?

**Comment by Doomsdayrs** [comment]
Thanks for commenting. This was meant to be a BetterDiscord plugin that would find a series of 6 numbers, check if it was an nhentai page, and prompt to view as nhentai

**Comment by ArisuSanchez** [comment]
yes, i know, i wanted this as i am in several servers that i moderate, and i would like to keep certain doujins out
